package cn.caijiajia.credittools.domain;

import java.util.Date;

public class HbUnionLoginLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hb_union_login_log.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hb_union_login_log.mobile
     *
     * @mbggenerated
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hb_union_login_log.channel
     *
     * @mbggenerated
     */
    private String channel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hb_union_login_log.uid
     *
     * @mbggenerated
     */
    private String uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hb_union_login_log.existed
     *
     * @mbggenerated
     */
    private Boolean existed;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hb_union_login_log.black_list
     *
     * @mbggenerated
     */
    private Boolean blackList;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hb_union_login_log.created_at
     *
     * @mbggenerated
     */
    private Date createdAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hb_union_login_log.updated_at
     *
     * @mbggenerated
     */
    private Date updatedAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hb_union_login_log.id
     *
     * @return the value of hb_union_login_log.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hb_union_login_log.id
     *
     * @param id the value for hb_union_login_log.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hb_union_login_log.mobile
     *
     * @return the value of hb_union_login_log.mobile
     *
     * @mbggenerated
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hb_union_login_log.mobile
     *
     * @param mobile the value for hb_union_login_log.mobile
     *
     * @mbggenerated
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hb_union_login_log.channel
     *
     * @return the value of hb_union_login_log.channel
     *
     * @mbggenerated
     */
    public String getChannel() {
        return channel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hb_union_login_log.channel
     *
     * @param channel the value for hb_union_login_log.channel
     *
     * @mbggenerated
     */
    public void setChannel(String channel) {
        this.channel = channel == null ? null : channel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hb_union_login_log.uid
     *
     * @return the value of hb_union_login_log.uid
     *
     * @mbggenerated
     */
    public String getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hb_union_login_log.uid
     *
     * @param uid the value for hb_union_login_log.uid
     *
     * @mbggenerated
     */
    public void setUid(String uid) {
        this.uid = uid == null ? null : uid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hb_union_login_log.existed
     *
     * @return the value of hb_union_login_log.existed
     *
     * @mbggenerated
     */
    public Boolean getExisted() {
        return existed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hb_union_login_log.existed
     *
     * @param existed the value for hb_union_login_log.existed
     *
     * @mbggenerated
     */
    public void setExisted(Boolean existed) {
        this.existed = existed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hb_union_login_log.black_list
     *
     * @return the value of hb_union_login_log.black_list
     *
     * @mbggenerated
     */
    public Boolean getBlackList() {
        return blackList;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hb_union_login_log.black_list
     *
     * @param blackList the value for hb_union_login_log.black_list
     *
     * @mbggenerated
     */
    public void setBlackList(Boolean blackList) {
        this.blackList = blackList;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hb_union_login_log.created_at
     *
     * @return the value of hb_union_login_log.created_at
     *
     * @mbggenerated
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hb_union_login_log.created_at
     *
     * @param createdAt the value for hb_union_login_log.created_at
     *
     * @mbggenerated
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hb_union_login_log.updated_at
     *
     * @return the value of hb_union_login_log.updated_at
     *
     * @mbggenerated
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hb_union_login_log.updated_at
     *
     * @param updatedAt the value for hb_union_login_log.updated_at
     *
     * @mbggenerated
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
}