package cn.caijiajia.credittools.domain;

public class ProductWithBLOBs extends Product {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.fee_rate
     *
     * @mbggenerated
     */
    private String feeRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.lend_period
     *
     * @mbggenerated
     */
    private String lendPeriod;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.promotion
     *
     * @mbggenerated
     */
    private String promotion;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.fee_rate
     *
     * @return the value of product.fee_rate
     *
     * @mbggenerated
     */
    public String getFeeRate() {
        return feeRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.fee_rate
     *
     * @param feeRate the value for product.fee_rate
     *
     * @mbggenerated
     */
    public void setFeeRate(String feeRate) {
        this.feeRate = feeRate == null ? null : feeRate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.lend_period
     *
     * @return the value of product.lend_period
     *
     * @mbggenerated
     */
    public String getLendPeriod() {
        return lendPeriod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.lend_period
     *
     * @param lendPeriod the value for product.lend_period
     *
     * @mbggenerated
     */
    public void setLendPeriod(String lendPeriod) {
        this.lendPeriod = lendPeriod == null ? null : lendPeriod.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.promotion
     *
     * @return the value of product.promotion
     *
     * @mbggenerated
     */
    public String getPromotion() {
        return promotion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.promotion
     *
     * @param promotion the value for product.promotion
     *
     * @mbggenerated
     */
    public void setPromotion(String promotion) {
        this.promotion = promotion == null ? null : promotion.trim();
    }
}