package cn.caijiajia.credittools.domain;

import java.util.Date;

public class Product {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.product_id
     *
     * @mbggenerated
     */
    private String productId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.onLineTime
     *
     * @mbggenerated
     */
    private Date onlinetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.offLineTime
     *
     * @mbggenerated
     */
    private Date offlinetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.status
     *
     * @mbggenerated
     */
    private Boolean status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.icon_url
     *
     * @mbggenerated
     */
    private String iconUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.mark
     *
     * @mbggenerated
     */
    private String mark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.min_amount
     *
     * @mbggenerated
     */
    private Integer minAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.max_amount
     *
     * @mbggenerated
     */
    private Integer maxAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.fee_rate
     *
     * @mbggenerated
     */
    private String feeRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.lend_period
     *
     * @mbggenerated
     */
    private String lendPeriod;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.show_fee_rate
     *
     * @mbggenerated
     */
    private Boolean showFeeRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.promotion
     *
     * @mbggenerated
     */
    private String promotion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.jump_url
     *
     * @mbggenerated
     */
    private String jumpUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.rank
     *
     * @mbggenerated
     */
    private Integer rank;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.tags
     *
     * @mbggenerated
     */
    private String tags;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.annual_rate
     *
     * @mbggenerated
     */
    private Double annualRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.lend_time
     *
     * @mbggenerated
     */
    private Double lendTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.pass_rate
     *
     * @mbggenerated
     */
    private Double passRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.aomount_first
     *
     * @mbggenerated
     */
    private Boolean aomountFirst;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.created_at
     *
     * @mbggenerated
     */
    private Date createdAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.updated_at
     *
     * @mbggenerated
     */
    private Date updatedAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.id
     *
     * @return the value of product.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.id
     *
     * @param id the value for product.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.product_id
     *
     * @return the value of product.product_id
     *
     * @mbggenerated
     */
    public String getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.product_id
     *
     * @param productId the value for product.product_id
     *
     * @mbggenerated
     */
    public void setProductId(String productId) {
        this.productId = productId == null ? null : productId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.name
     *
     * @return the value of product.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.name
     *
     * @param name the value for product.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.onLineTime
     *
     * @return the value of product.onLineTime
     *
     * @mbggenerated
     */
    public Date getOnlinetime() {
        return onlinetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.onLineTime
     *
     * @param onlinetime the value for product.onLineTime
     *
     * @mbggenerated
     */
    public void setOnlinetime(Date onlinetime) {
        this.onlinetime = onlinetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.offLineTime
     *
     * @return the value of product.offLineTime
     *
     * @mbggenerated
     */
    public Date getOfflinetime() {
        return offlinetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.offLineTime
     *
     * @param offlinetime the value for product.offLineTime
     *
     * @mbggenerated
     */
    public void setOfflinetime(Date offlinetime) {
        this.offlinetime = offlinetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.status
     *
     * @return the value of product.status
     *
     * @mbggenerated
     */
    public Boolean getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.status
     *
     * @param status the value for product.status
     *
     * @mbggenerated
     */
    public void setStatus(Boolean status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.icon_url
     *
     * @return the value of product.icon_url
     *
     * @mbggenerated
     */
    public String getIconUrl() {
        return iconUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.icon_url
     *
     * @param iconUrl the value for product.icon_url
     *
     * @mbggenerated
     */
    public void setIconUrl(String iconUrl) {
        this.iconUrl = iconUrl == null ? null : iconUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.mark
     *
     * @return the value of product.mark
     *
     * @mbggenerated
     */
    public String getMark() {
        return mark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.mark
     *
     * @param mark the value for product.mark
     *
     * @mbggenerated
     */
    public void setMark(String mark) {
        this.mark = mark == null ? null : mark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.min_amount
     *
     * @return the value of product.min_amount
     *
     * @mbggenerated
     */
    public Integer getMinAmount() {
        return minAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.min_amount
     *
     * @param minAmount the value for product.min_amount
     *
     * @mbggenerated
     */
    public void setMinAmount(Integer minAmount) {
        this.minAmount = minAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.max_amount
     *
     * @return the value of product.max_amount
     *
     * @mbggenerated
     */
    public Integer getMaxAmount() {
        return maxAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.max_amount
     *
     * @param maxAmount the value for product.max_amount
     *
     * @mbggenerated
     */
    public void setMaxAmount(Integer maxAmount) {
        this.maxAmount = maxAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.fee_rate
     *
     * @return the value of product.fee_rate
     *
     * @mbggenerated
     */
    public String getFeeRate() {
        return feeRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.fee_rate
     *
     * @param feeRate the value for product.fee_rate
     *
     * @mbggenerated
     */
    public void setFeeRate(String feeRate) {
        this.feeRate = feeRate == null ? null : feeRate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.lend_period
     *
     * @return the value of product.lend_period
     *
     * @mbggenerated
     */
    public String getLendPeriod() {
        return lendPeriod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.lend_period
     *
     * @param lendPeriod the value for product.lend_period
     *
     * @mbggenerated
     */
    public void setLendPeriod(String lendPeriod) {
        this.lendPeriod = lendPeriod == null ? null : lendPeriod.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.show_fee_rate
     *
     * @return the value of product.show_fee_rate
     *
     * @mbggenerated
     */
    public Boolean getShowFeeRate() {
        return showFeeRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.show_fee_rate
     *
     * @param showFeeRate the value for product.show_fee_rate
     *
     * @mbggenerated
     */
    public void setShowFeeRate(Boolean showFeeRate) {
        this.showFeeRate = showFeeRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.promotion
     *
     * @return the value of product.promotion
     *
     * @mbggenerated
     */
    public String getPromotion() {
        return promotion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.promotion
     *
     * @param promotion the value for product.promotion
     *
     * @mbggenerated
     */
    public void setPromotion(String promotion) {
        this.promotion = promotion == null ? null : promotion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.jump_url
     *
     * @return the value of product.jump_url
     *
     * @mbggenerated
     */
    public String getJumpUrl() {
        return jumpUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.jump_url
     *
     * @param jumpUrl the value for product.jump_url
     *
     * @mbggenerated
     */
    public void setJumpUrl(String jumpUrl) {
        this.jumpUrl = jumpUrl == null ? null : jumpUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.rank
     *
     * @return the value of product.rank
     *
     * @mbggenerated
     */
    public Integer getRank() {
        return rank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.rank
     *
     * @param rank the value for product.rank
     *
     * @mbggenerated
     */
    public void setRank(Integer rank) {
        this.rank = rank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.tags
     *
     * @return the value of product.tags
     *
     * @mbggenerated
     */
    public String getTags() {
        return tags;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.tags
     *
     * @param tags the value for product.tags
     *
     * @mbggenerated
     */
    public void setTags(String tags) {
        this.tags = tags == null ? null : tags.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.annual_rate
     *
     * @return the value of product.annual_rate
     *
     * @mbggenerated
     */
    public Double getAnnualRate() {
        return annualRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.annual_rate
     *
     * @param annualRate the value for product.annual_rate
     *
     * @mbggenerated
     */
    public void setAnnualRate(Double annualRate) {
        this.annualRate = annualRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.lend_time
     *
     * @return the value of product.lend_time
     *
     * @mbggenerated
     */
    public Double getLendTime() {
        return lendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.lend_time
     *
     * @param lendTime the value for product.lend_time
     *
     * @mbggenerated
     */
    public void setLendTime(Double lendTime) {
        this.lendTime = lendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.pass_rate
     *
     * @return the value of product.pass_rate
     *
     * @mbggenerated
     */
    public Double getPassRate() {
        return passRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.pass_rate
     *
     * @param passRate the value for product.pass_rate
     *
     * @mbggenerated
     */
    public void setPassRate(Double passRate) {
        this.passRate = passRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.aomount_first
     *
     * @return the value of product.aomount_first
     *
     * @mbggenerated
     */
    public Boolean getAomountFirst() {
        return aomountFirst;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.aomount_first
     *
     * @param aomountFirst the value for product.aomount_first
     *
     * @mbggenerated
     */
    public void setAomountFirst(Boolean aomountFirst) {
        this.aomountFirst = aomountFirst;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.created_at
     *
     * @return the value of product.created_at
     *
     * @mbggenerated
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.created_at
     *
     * @param createdAt the value for product.created_at
     *
     * @mbggenerated
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.updated_at
     *
     * @return the value of product.updated_at
     *
     * @mbggenerated
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.updated_at
     *
     * @param updatedAt the value for product.updated_at
     *
     * @mbggenerated
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;

        Product product = (Product) o;

        return id.equals(product.id);
    }

    @Override
    public int hashCode() {
        return id.hashCode();
    }
}