package cn.caijiajia.credittools.mapper;

import cn.caijiajia.credittools.bo.ProductClickNumBo;
import cn.caijiajia.credittools.domain.ProductClickLog;
import cn.caijiajia.credittools.domain.ProductClickLogExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface ProductClickLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_click_log
     *
     * @mbggenerated
     */
    int countByExample(ProductClickLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_click_log
     *
     * @mbggenerated
     */
    int deleteByExample(ProductClickLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_click_log
     *
     * @mbggenerated
     */
    @Delete({
        "delete from `product_click_log`",
        "where `id` = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_click_log
     *
     * @mbggenerated
     */
    @Insert({
        "insert into `product_click_log` (`id`, `uid`, ",
        "`product_id`, `click_time`, ",
        "`created_at`, `updated_at`)",
        "values (#{id,jdbcType=INTEGER}, #{uid,jdbcType=VARCHAR}, ",
        "#{productId,jdbcType=INTEGER}, #{clickTime,jdbcType=INTEGER}, ",
        "#{createdAt,jdbcType=TIMESTAMP}, #{updatedAt,jdbcType=TIMESTAMP})"
    })
    int insert(ProductClickLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_click_log
     *
     * @mbggenerated
     */
    int insertSelective(ProductClickLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_click_log
     *
     * @mbggenerated
     */
    List<ProductClickLog> selectByExample(ProductClickLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_click_log
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "`id`, `uid`, `product_id`, `click_time`, `created_at`, `updated_at`",
        "from `product_click_log`",
        "where `id` = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("BaseResultMap")
    ProductClickLog selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_click_log
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") ProductClickLog record, @Param("example") ProductClickLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_click_log
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") ProductClickLog record, @Param("example") ProductClickLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_click_log
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ProductClickLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_click_log
     *
     * @mbggenerated
     */
    @Update({
        "update `product_click_log`",
        "set `uid` = #{uid,jdbcType=VARCHAR},",
          "`product_id` = #{productId,jdbcType=INTEGER},",
          "`click_time` = #{clickTime,jdbcType=INTEGER},",
          "`created_at` = #{createdAt,jdbcType=TIMESTAMP},",
          "`updated_at` = #{updatedAt,jdbcType=TIMESTAMP}",
        "where `id` = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(ProductClickLog record);

    List<ProductClickNumBo> getProductNum();

    int insertAndClickTimeIncre(ProductClickLog record);
}