package cn.caijiajia.credittools.mapper;

import cn.caijiajia.credittools.domain.Product;
import cn.caijiajia.credittools.domain.ProductExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface ProductMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated
     */
    int countByExample(ProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated
     */
    int deleteByExample(ProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated
     */
    @Delete({
        "delete from `product`",
        "where `id` = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated
     */
    @Insert({
        "insert into `product` (`id`, `product_id`, ",
        "`name`, `onLineTime`, ",
        "`offLineTime`, `status`, ",
        "`icon_url`, `mark`, `min_amount`, ",
        "`max_amount`, `fee_rate`, ",
        "`lend_period`, `show_fee_rate`, ",
        "`promotion`, `jump_url`, ",
        "`rank`, `tags`, `annual_rate`, ",
        "`lend_time`, `pass_rate`, ",
        "`aomount_first`, `created_at`, ",
        "`updated_at`)",
        "values (#{id,jdbcType=INTEGER}, #{productId,jdbcType=VARCHAR}, ",
        "#{name,jdbcType=VARCHAR}, #{onlinetime,jdbcType=TIMESTAMP}, ",
        "#{offlinetime,jdbcType=TIMESTAMP}, #{status,jdbcType=BIT}, ",
        "#{iconUrl,jdbcType=VARCHAR}, #{mark,jdbcType=VARCHAR}, #{minAmount,jdbcType=INTEGER}, ",
        "#{maxAmount,jdbcType=INTEGER}, #{feeRate,jdbcType=VARCHAR}, ",
        "#{lendPeriod,jdbcType=VARCHAR}, #{showFeeRate,jdbcType=BIT}, ",
        "#{promotion,jdbcType=VARCHAR}, #{jumpUrl,jdbcType=VARCHAR}, ",
        "#{rank,jdbcType=INTEGER}, #{tags,jdbcType=VARCHAR}, #{annualRate,jdbcType=DOUBLE}, ",
        "#{lendTime,jdbcType=DOUBLE}, #{passRate,jdbcType=DOUBLE}, ",
        "#{aomountFirst,jdbcType=BIT}, #{createdAt,jdbcType=TIMESTAMP}, ",
        "#{updatedAt,jdbcType=TIMESTAMP})"
    })
    int insert(Product record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated
     */
    int insertSelective(Product record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated
     */
    List<Product> selectByExample(ProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "`id`, `product_id`, `name`, `onLineTime`, `offLineTime`, `status`, `icon_url`, ",
        "`mark`, `min_amount`, `max_amount`, `fee_rate`, `lend_period`, `show_fee_rate`, ",
        "`promotion`, `jump_url`, `rank`, `tags`, `annual_rate`, `lend_time`, `pass_rate`, ",
        "`aomount_first`, `created_at`, `updated_at`",
        "from `product`",
        "where `id` = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("BaseResultMap")
    Product selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Product record, @Param("example") ProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Product record, @Param("example") ProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Product record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated
     */
    @Update({
        "update `product`",
        "set `product_id` = #{productId,jdbcType=VARCHAR},",
          "`name` = #{name,jdbcType=VARCHAR},",
          "`onLineTime` = #{onlinetime,jdbcType=TIMESTAMP},",
          "`offLineTime` = #{offlinetime,jdbcType=TIMESTAMP},",
          "`status` = #{status,jdbcType=BIT},",
          "`icon_url` = #{iconUrl,jdbcType=VARCHAR},",
          "`mark` = #{mark,jdbcType=VARCHAR},",
          "`min_amount` = #{minAmount,jdbcType=INTEGER},",
          "`max_amount` = #{maxAmount,jdbcType=INTEGER},",
          "`fee_rate` = #{feeRate,jdbcType=VARCHAR},",
          "`lend_period` = #{lendPeriod,jdbcType=VARCHAR},",
          "`show_fee_rate` = #{showFeeRate,jdbcType=BIT},",
          "`promotion` = #{promotion,jdbcType=VARCHAR},",
          "`jump_url` = #{jumpUrl,jdbcType=VARCHAR},",
          "`rank` = #{rank,jdbcType=INTEGER},",
          "`tags` = #{tags,jdbcType=VARCHAR},",
          "`annual_rate` = #{annualRate,jdbcType=DOUBLE},",
          "`lend_time` = #{lendTime,jdbcType=DOUBLE},",
          "`pass_rate` = #{passRate,jdbcType=DOUBLE},",
          "`aomount_first` = #{aomountFirst,jdbcType=BIT},",
          "`created_at` = #{createdAt,jdbcType=TIMESTAMP},",
          "`updated_at` = #{updatedAt,jdbcType=TIMESTAMP}",
        "where `id` = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Product record);
}