package cn.caijiajia.credittools.mapper;

import cn.caijiajia.credittools.domain.Product;
import cn.caijiajia.credittools.domain.ProductExample;
import cn.caijiajia.credittools.domain.ProductWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface ProductMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated
     */
    int countByExample(ProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated
     */
    int deleteByExample(ProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated
     */
    @Delete({
        "delete from `product`",
        "where `id` = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated
     */
    @Insert({
        "insert into `product` (`id`, `product_id`, ",
        "`name`, `onLineTime`, ",
        "`offLineTime`, `status`, ",
        "`icon_url`, `mark`, `min_amount`, ",
        "`max_amount`, `show_fee_rate`, ",
        "`jump_url`, `rank`, `tags`, ",
        "`annual_rate`, `lend_time`, ",
        "`pass_rate`, `aomount_first`, ",
        "`created_at`, `updated_at`, ",
        "`fee_rate`, `lend_period`, ",
        "`promotion`)",
        "values (#{id,jdbcType=INTEGER}, #{productId,jdbcType=VARCHAR}, ",
        "#{name,jdbcType=VARCHAR}, #{onlinetime,jdbcType=TIMESTAMP}, ",
        "#{offlinetime,jdbcType=TIMESTAMP}, #{status,jdbcType=BIT}, ",
        "#{iconUrl,jdbcType=VARCHAR}, #{mark,jdbcType=VARCHAR}, #{minAmount,jdbcType=INTEGER}, ",
        "#{maxAmount,jdbcType=INTEGER}, #{showFeeRate,jdbcType=BIT}, ",
        "#{jumpUrl,jdbcType=VARCHAR}, #{rank,jdbcType=INTEGER}, #{tags,jdbcType=VARCHAR}, ",
        "#{annualRate,jdbcType=DECIMAL}, #{lendTime,jdbcType=DECIMAL}, ",
        "#{passRate,jdbcType=DECIMAL}, #{aomountFirst,jdbcType=BIT}, ",
        "#{createdAt,jdbcType=TIMESTAMP}, #{updatedAt,jdbcType=TIMESTAMP}, ",
        "#{feeRate,jdbcType=LONGVARCHAR}, #{lendPeriod,jdbcType=LONGVARCHAR}, ",
        "#{promotion,jdbcType=LONGVARCHAR})"
    })
    int insert(ProductWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated
     */
    int insertSelective(ProductWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated
     */
    List<ProductWithBLOBs> selectByExampleWithBLOBs(ProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated
     */
    List<Product> selectByExample(ProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "`id`, `product_id`, `name`, `onLineTime`, `offLineTime`, `status`, `icon_url`, ",
        "`mark`, `min_amount`, `max_amount`, `show_fee_rate`, `jump_url`, `rank`, `tags`, ",
        "`annual_rate`, `lend_time`, `pass_rate`, `aomount_first`, `created_at`, `updated_at`, ",
        "`fee_rate`, `lend_period`, `promotion`",
        "from `product`",
        "where `id` = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("ResultMapWithBLOBs")
    ProductWithBLOBs selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") ProductWithBLOBs record, @Param("example") ProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated
     */
    int updateByExampleWithBLOBs(@Param("record") ProductWithBLOBs record, @Param("example") ProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Product record, @Param("example") ProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ProductWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated
     */
    @Update({
        "update `product`",
        "set `product_id` = #{productId,jdbcType=VARCHAR},",
          "`name` = #{name,jdbcType=VARCHAR},",
          "`onLineTime` = #{onlinetime,jdbcType=TIMESTAMP},",
          "`offLineTime` = #{offlinetime,jdbcType=TIMESTAMP},",
          "`status` = #{status,jdbcType=BIT},",
          "`icon_url` = #{iconUrl,jdbcType=VARCHAR},",
          "`mark` = #{mark,jdbcType=VARCHAR},",
          "`min_amount` = #{minAmount,jdbcType=INTEGER},",
          "`max_amount` = #{maxAmount,jdbcType=INTEGER},",
          "`show_fee_rate` = #{showFeeRate,jdbcType=BIT},",
          "`jump_url` = #{jumpUrl,jdbcType=VARCHAR},",
          "`rank` = #{rank,jdbcType=INTEGER},",
          "`tags` = #{tags,jdbcType=VARCHAR},",
          "`annual_rate` = #{annualRate,jdbcType=DECIMAL},",
          "`lend_time` = #{lendTime,jdbcType=DECIMAL},",
          "`pass_rate` = #{passRate,jdbcType=DECIMAL},",
          "`aomount_first` = #{aomountFirst,jdbcType=BIT},",
          "`created_at` = #{createdAt,jdbcType=TIMESTAMP},",
          "`updated_at` = #{updatedAt,jdbcType=TIMESTAMP},",
          "`fee_rate` = #{feeRate,jdbcType=LONGVARCHAR},",
          "`lend_period` = #{lendPeriod,jdbcType=LONGVARCHAR},",
          "`promotion` = #{promotion,jdbcType=LONGVARCHAR}",
        "where `id` = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKeyWithBLOBs(ProductWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated
     */
    @Update({
        "update `product`",
        "set `product_id` = #{productId,jdbcType=VARCHAR},",
          "`name` = #{name,jdbcType=VARCHAR},",
          "`onLineTime` = #{onlinetime,jdbcType=TIMESTAMP},",
          "`offLineTime` = #{offlinetime,jdbcType=TIMESTAMP},",
          "`status` = #{status,jdbcType=BIT},",
          "`icon_url` = #{iconUrl,jdbcType=VARCHAR},",
          "`mark` = #{mark,jdbcType=VARCHAR},",
          "`min_amount` = #{minAmount,jdbcType=INTEGER},",
          "`max_amount` = #{maxAmount,jdbcType=INTEGER},",
          "`show_fee_rate` = #{showFeeRate,jdbcType=BIT},",
          "`jump_url` = #{jumpUrl,jdbcType=VARCHAR},",
          "`rank` = #{rank,jdbcType=INTEGER},",
          "`tags` = #{tags,jdbcType=VARCHAR},",
          "`annual_rate` = #{annualRate,jdbcType=DECIMAL},",
          "`lend_time` = #{lendTime,jdbcType=DECIMAL},",
          "`pass_rate` = #{passRate,jdbcType=DECIMAL},",
          "`aomount_first` = #{aomountFirst,jdbcType=BIT},",
          "`created_at` = #{createdAt,jdbcType=TIMESTAMP},",
          "`updated_at` = #{updatedAt,jdbcType=TIMESTAMP}",
        "where `id` = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Product record);
}