package cn.caijiajia.credittools.mapper;

import cn.caijiajia.credittools.domain.UnionLoginLog;
import cn.caijiajia.credittools.domain.UnionLoginLogExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface UnionLoginLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table union_login_log
     *
     * @mbggenerated
     */
    int countByExample(UnionLoginLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table union_login_log
     *
     * @mbggenerated
     */
    int deleteByExample(UnionLoginLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table union_login_log
     *
     * @mbggenerated
     */
    @Delete({
        "delete from `union_login_log`",
        "where `id` = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table union_login_log
     *
     * @mbggenerated
     */
    @Insert({
        "insert into `union_login_log` (`id`, `uid`, ",
        "`channel`, `mobile`, ",
        "`old_user`, `created_at`, ",
        "`updated_at`)",
        "values (#{id,jdbcType=BIGINT}, #{uid,jdbcType=VARCHAR}, ",
        "#{channel,jdbcType=VARCHAR}, #{mobile,jdbcType=VARCHAR}, ",
        "#{oldUser,jdbcType=BIT}, #{createdAt,jdbcType=TIMESTAMP}, ",
        "#{updatedAt,jdbcType=TIMESTAMP})"
    })
    int insert(UnionLoginLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table union_login_log
     *
     * @mbggenerated
     */
    int insertSelective(UnionLoginLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table union_login_log
     *
     * @mbggenerated
     */
    List<UnionLoginLog> selectByExample(UnionLoginLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table union_login_log
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "`id`, `uid`, `channel`, `mobile`, `old_user`, `created_at`, `updated_at`",
        "from `union_login_log`",
        "where `id` = #{id,jdbcType=BIGINT}"
    })
    @ResultMap("BaseResultMap")
    UnionLoginLog selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table union_login_log
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") UnionLoginLog record, @Param("example") UnionLoginLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table union_login_log
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") UnionLoginLog record, @Param("example") UnionLoginLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table union_login_log
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(UnionLoginLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table union_login_log
     *
     * @mbggenerated
     */
    @Update({
        "update `union_login_log`",
        "set `uid` = #{uid,jdbcType=VARCHAR},",
          "`channel` = #{channel,jdbcType=VARCHAR},",
          "`mobile` = #{mobile,jdbcType=VARCHAR},",
          "`old_user` = #{oldUser,jdbcType=BIT},",
          "`created_at` = #{createdAt,jdbcType=TIMESTAMP},",
          "`updated_at` = #{updatedAt,jdbcType=TIMESTAMP}",
        "where `id` = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(UnionLoginLog record);
}